/*
Generated by Bit OS Machine Langauge Compiler
File: code.bml
Total Size: 76 bytes
Time Compiled: 2023-04-29, 10:32 PM

Data Memory Locations
  $print: 20
  $end_print: 62
  $str: 63
*/
#include <stdint.h>
#define EXE_SIZE 76
uint8_t exeContent[] = {
  30, 29, 0, 0, 0, 0, 0, 0, 0, 63, 
  27, 0, 0, 0, 0, 0, 0, 0, 20, 
  0, 
  19, 29, 0, 
  22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  23, 0, 0, 0, 0, 0, 0, 0, 62, 
  28, 
  5, 29, 0, 0, 0, 0, 0, 0, 0, 1, 
  27, 0, 0, 0, 0, 0, 0, 0, 20, 
  0, 
  72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33, 0, 
};